### ISSUE TITLE
CRUD - Create routes for load details to access back end api

### ISSUE THREAD

**Issue by Singh2je** [lizbissinger/Senior-Design-Front-End#17]
1. Create CRUD endpoints in the front-end that utilize endpoints in backend.

Create a delete prompt to when deleting.

**Comment by sekhonsj** [comment]
**TWO PULL REQUESTS ASSOCIATED - 
FRONT:** https://github.com/lizbissinger/Senior-Design-Front-End/pull/44
**BACK:** https://github.com/lizbissinger/Senior-Design-Back-End/pull/13
